# Generated by Django 5.1.4 on 2024-12-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(default=0, max_length=100, verbose_name='штук'),
        ),
        migrations.AlterField(
            model_name='products',
            name='grams',
            field=models.CharField(max_length=100, verbose_name='Граммы'),
        ),
    ]
