# Generated by Django 5.1.4 on 2024-12-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_quantity_alter_products_grams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
