# Generated by Django 5.1.4 on 2024-12-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categoty',
            new_name='category',
        ),
    ]
